version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/weather_ui/
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 30000
      runas: root
  AfterInstall:
    - location: scripts/startup.sh
      timeout: 30000
      runas: root
